package com.clogcompanion.model;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import net.runelite.api.Varbits;

/** Achievement diary completion varbits by their {@link Varbits} constant name. */
public final class Diaries
{
	public static final Map<String, Integer> BY_NAME;

	static
	{
		Map<String, Integer> m = new LinkedHashMap<>();
		m.put("DIARY_ARDOUGNE_EASY", Varbits.DIARY_ARDOUGNE_EASY);
		m.put("DIARY_ARDOUGNE_MEDIUM", Varbits.DIARY_ARDOUGNE_MEDIUM);
		m.put("DIARY_ARDOUGNE_HARD", Varbits.DIARY_ARDOUGNE_HARD);
		m.put("DIARY_ARDOUGNE_ELITE", Varbits.DIARY_ARDOUGNE_ELITE);
		m.put("DIARY_DESERT_EASY", Varbits.DIARY_DESERT_EASY);
		m.put("DIARY_DESERT_MEDIUM", Varbits.DIARY_DESERT_MEDIUM);
		m.put("DIARY_DESERT_HARD", Varbits.DIARY_DESERT_HARD);
		m.put("DIARY_DESERT_ELITE", Varbits.DIARY_DESERT_ELITE);
		m.put("DIARY_FALADOR_EASY", Varbits.DIARY_FALADOR_EASY);
		m.put("DIARY_FALADOR_MEDIUM", Varbits.DIARY_FALADOR_MEDIUM);
		m.put("DIARY_FALADOR_HARD", Varbits.DIARY_FALADOR_HARD);
		m.put("DIARY_FALADOR_ELITE", Varbits.DIARY_FALADOR_ELITE);
		m.put("DIARY_FREMENNIK_EASY", Varbits.DIARY_FREMENNIK_EASY);
		m.put("DIARY_FREMENNIK_MEDIUM", Varbits.DIARY_FREMENNIK_MEDIUM);
		m.put("DIARY_FREMENNIK_HARD", Varbits.DIARY_FREMENNIK_HARD);
		m.put("DIARY_FREMENNIK_ELITE", Varbits.DIARY_FREMENNIK_ELITE);
		m.put("DIARY_KANDARIN_EASY", Varbits.DIARY_KANDARIN_EASY);
		m.put("DIARY_KANDARIN_MEDIUM", Varbits.DIARY_KANDARIN_MEDIUM);
		m.put("DIARY_KANDARIN_HARD", Varbits.DIARY_KANDARIN_HARD);
		m.put("DIARY_KANDARIN_ELITE", Varbits.DIARY_KANDARIN_ELITE);
		m.put("DIARY_KARAMJA_EASY", Varbits.DIARY_KARAMJA_EASY);
		m.put("DIARY_KARAMJA_MEDIUM", Varbits.DIARY_KARAMJA_MEDIUM);
		m.put("DIARY_KARAMJA_HARD", Varbits.DIARY_KARAMJA_HARD);
		m.put("DIARY_KARAMJA_ELITE", Varbits.DIARY_KARAMJA_ELITE);
		m.put("DIARY_KOUREND_EASY", Varbits.DIARY_KOUREND_EASY);
		m.put("DIARY_KOUREND_MEDIUM", Varbits.DIARY_KOUREND_MEDIUM);
		m.put("DIARY_KOUREND_HARD", Varbits.DIARY_KOUREND_HARD);
		m.put("DIARY_KOUREND_ELITE", Varbits.DIARY_KOUREND_ELITE);
		m.put("DIARY_LUMBRIDGE_EASY", Varbits.DIARY_LUMBRIDGE_EASY);
		m.put("DIARY_LUMBRIDGE_MEDIUM", Varbits.DIARY_LUMBRIDGE_MEDIUM);
		m.put("DIARY_LUMBRIDGE_HARD", Varbits.DIARY_LUMBRIDGE_HARD);
		m.put("DIARY_LUMBRIDGE_ELITE", Varbits.DIARY_LUMBRIDGE_ELITE);
		m.put("DIARY_MORYTANIA_EASY", Varbits.DIARY_MORYTANIA_EASY);
		m.put("DIARY_MORYTANIA_MEDIUM", Varbits.DIARY_MORYTANIA_MEDIUM);
		m.put("DIARY_MORYTANIA_HARD", Varbits.DIARY_MORYTANIA_HARD);
		m.put("DIARY_MORYTANIA_ELITE", Varbits.DIARY_MORYTANIA_ELITE);
		m.put("DIARY_VARROCK_EASY", Varbits.DIARY_VARROCK_EASY);
		m.put("DIARY_VARROCK_MEDIUM", Varbits.DIARY_VARROCK_MEDIUM);
		m.put("DIARY_VARROCK_HARD", Varbits.DIARY_VARROCK_HARD);
		m.put("DIARY_VARROCK_ELITE", Varbits.DIARY_VARROCK_ELITE);
		m.put("DIARY_WESTERN_EASY", Varbits.DIARY_WESTERN_EASY);
		m.put("DIARY_WESTERN_MEDIUM", Varbits.DIARY_WESTERN_MEDIUM);
		m.put("DIARY_WESTERN_HARD", Varbits.DIARY_WESTERN_HARD);
		m.put("DIARY_WESTERN_ELITE", Varbits.DIARY_WESTERN_ELITE);
		m.put("DIARY_WILDERNESS_EASY", Varbits.DIARY_WILDERNESS_EASY);
		m.put("DIARY_WILDERNESS_MEDIUM", Varbits.DIARY_WILDERNESS_MEDIUM);
		m.put("DIARY_WILDERNESS_HARD", Varbits.DIARY_WILDERNESS_HARD);
		m.put("DIARY_WILDERNESS_ELITE", Varbits.DIARY_WILDERNESS_ELITE);
		BY_NAME = Collections.unmodifiableMap(m);
	}

	private Diaries()
	{
	}
}
